[package]
name = "tmon"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
arboard.workspace = true
diagnostics = { path = "../diagnostics" }
engine = { path = "../engine" }
mux = { path = "../mux" }
render = { path = "../render" }
pollster.workspace = true
serde.workspace = true
serde_json.workspace = true
toml_edit.workspace = true
winit.workspace = true

[lints]
workspace = true
