[package]
name = "termy_multiplexer"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
bincode = "1.3.3"
flume = { workspace = true }
fs4 = { version = "0.13.1", features = ["sync"] }
log = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
termy_core = { path = "../core" }
uuid = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = { workspace = true }

[[bin]]
name = "termy-session-host"
path = "src/main.rs"
