/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthOauthCompleteRouteImport } from './routes/_auth/oauth-complete'
import { Route as AuthDeviceRouteImport } from './routes/_auth/device'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOauthCompleteRoute = AuthOauthCompleteRouteImport.update({
  id: '/oauth-complete',
  path: '/oauth-complete',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device': typeof AuthDeviceRoute
  '/oauth-complete': typeof AuthOauthCompleteRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/device': typeof AuthDeviceRoute
  '/oauth-complete': typeof AuthOauthCompleteRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_auth/device': typeof AuthDeviceRoute
  '/_auth/oauth-complete': typeof AuthOauthCompleteRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/_auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/device'
    | '/oauth-complete'
    | '/register'
    | '/dashboard/projects'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/device'
    | '/oauth-complete'
    | '/register'
    | '/dashboard/projects'
    | '/'
    | '/dashboard'
  id:
    | '__root__'
    | '/_auth'
    | '/dashboard'
    | '/_auth/device'
    | '/_auth/oauth-complete'
    | '/_auth/register'
    | '/dashboard/projects'
    | '/_auth/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/oauth-complete': {
      id: '/_auth/oauth-complete'
      path: '/oauth-complete'
      fullPath: '/oauth-complete'
      preLoaderRoute: typeof AuthOauthCompleteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/device': {
      id: '/_auth/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDeviceRoute: typeof AuthDeviceRoute
  AuthOauthCompleteRoute: typeof AuthOauthCompleteRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDeviceRoute: AuthDeviceRoute,
  AuthOauthCompleteRoute: AuthOauthCompleteRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
