[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
bitflags = { workspace = true, features = ["serde"] }
libc.workspace = true
postcard.workspace = true
serde.workspace = true
smol_str.workspace = true
unicode-width.workspace = true
vte.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints.rust]
unsafe_code = "deny"
missing_debug_implementations = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
undocumented_unsafe_blocks = "deny"
module_name_repetitions = "allow"
too_many_lines = "allow"
