[package]
name = "termy_core"
version = "0.2.0"
edition = "2024"
license = "MIT"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
alacritty_terminal = { workspace = true }
base64 = "0.22"
compact_str = { version = "0.8.1", features = ["serde"] }
serde = { workspace = true, features = ["rc"] }
flume = { workspace = true }
log = { workspace = true }
dirs = { workspace = true }
flate2 = "1.1"
fontdb = "0.23"
polling = { workspace = true }
png = "0.18"
rand_core = { workspace = true }
termy_config_core = { path = "../config_core" }
termy_search = { path = "../search" }
termy_themes = { path = "../themes" }
tmon = { path = "../tmon" }
ttf-parser = "0.25"
unicode-width = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix-openpty = "0.2"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"

[dev-dependencies]
tempfile = { workspace = true }
